openapi: 3.1.0
x-stoplight:
  id: 3zlaz714ownj1
info:
  title: SimXML
  version: '1.0'
  summary: SimXML api for translations
  contact:
    name: Conduction
    url: conduction.nl
    email: info@conduction.nl
  license:
    name: EUPL 1.2
    identifier: EUPL-1.2
  description: SimXML api for translations
servers: []
paths:
  /simxml:
    parameters: []
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimXML'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
            application/xml:
              schema:
                $ref: '#/components/schemas/SimXML'
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
    post:
      summary: ''
      operationId: post-simxml
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimXML'
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/SimXML'
components:
  schemas:
    SimXML:
      title: SimXML
      x-stoplight:
        id: chmsyzt2qzvgo
      type: object
      properties:
        stuurgegevens:
          $ref: '#/components/schemas/Stuurgegevens'
        body:
          $ref: '#/components/schemas/Body'
        bijlagen:
          type: array
          items:
            $ref: '#/components/schemas/Bijlage'
        zgwZaak:
          type: string
        zgwDocumenten:
          type: array
          items:
            type: string
        parameters:
          type: object
          properties:
            mutatiesoort:
              type: string
            indicatorOvername:
              type: string
    Stuurgegevens:
      title: Stuurgegevens
      x-stoplight:
        id: hlp7552ghfwlf
      type: object
      properties:
        zaaktype:
          type: string
        versie:
          type: string
        berichttype:
          type: string
        zender:
          type: string
        ontvanger:
          type: string
        sleutel:
          type: string
        datum:
          type: string
        berichtcode:
          type: string
        referentienummer:
          type: string
        entiteittype:
          type: string
    Body:
      title: Body
      x-stoplight:
        id: ipte2i3snddkd
      type: object
      properties:
        formulierId:
          type: string
        datumVerzending:
          type: string
        metadata:
          $ref: '#/components/schemas/Metadata'
        elementen:
          $ref: '#/components/schemas/Elementen'
    Metadata:
      title: Metadata
      x-stoplight:
        id: nshh02t4uuvrf
      type: object
      properties:
        id:
          type: string
        zaaktype:
          type: string
        zaakId:
          type: string
        code_kanaal:
          type: string
        code_medewerker:
          type: string
        indiener:
          type: string
        indienersoort:
          type: string
        betrouwbaarheid_identificatie:
          type: string
        betrouwbaarheid_naw:
          type: string
        oGone_orderId:
          type: string
        oGone_status:
          type: string
    Bijlage:
      title: Bijlage
      x-stoplight:
        id: k2l7299by14mx
      type: object
      properties:
        naam:
          type: string
        omschrijving:
          type: string
        inhoud:
          type: object
          properties:
            contentType:
              type: string
            content:
              type: string
    IntraRelocation:
      title: IntraRelocation
      x-stoplight:
        id: k1huigdqpv93q
      type: object
      description: A relocation in the same municipality
      properties:
        dossier:
          $ref: '#/components/schemas/Dossier'
        declarant:
          $ref: '#/components/schemas/Declarant'
        newAddress:
          $ref: '#/components/schemas/NewAddress'
        relocators:
          type: array
          items:
            $ref: '#/components/schemas/Relocators'
    Commitment:
      title: Commitment
      x-stoplight:
        id: vtb1gpeahkdbx
      type: object
      properties:
        dossier:
          $ref: '#/components/schemas/Dossier'
        partner1:
          $ref: '#/components/schemas/Partner'
        partner2:
          $ref: '#/components/schemas/Partner'
        planning:
          type: object
          properties:
            commitmentType:
              type: string
            commitmentDateTime:
              type: string
            intentionDate:
              type: string
            remarks:
              type: string
        location:
          type: object
          properties:
            name:
              type: string
            aliases:
              type: array
              items: {}
            options:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  value:
                    type: string
                  description:
                    type: string
                  type:
                    type: string
                  aliases:
                    type: array
                    items: {}
        officials:
          type: object
          properties:
            preferences:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  contactInformation:
                    $ref: '#/components/schemas/ContactInformation'
                  aliases:
                    type: array
                    items: {}
            assigned:
              type: object
              properties:
                name:
                  type: string
                contactInformation:
                  $ref: '#/components/schemas/ContactInformation'
                aliases:
                  type: array
                  items: {}
        witnesses:
          type: object
          properties:
            numberOfMunicipalWitnesses:
              type: integer
            chosen:
              type: array
              items:
                type: object
                properties:
                  bsn:
                    type: string
                  firstname:
                    type: string
                  prefix:
                    type: string
                  lastname:
                    type: string
                  birthdate:
                    type: integer
                  remarks:
                    type: string
    InterRelocation:
      title: InterRelocation
      x-stoplight:
        id: 589m5aeriauxh
      type: object
      description: A relocation to a different municipality
      properties:
        dossier:
          $ref: '#/components/schemas/Dossier'
        declarant:
          $ref: '#/components/schemas/Declarant'
        newAddress:
          $ref: '#/components/schemas/NewAddress'
        previousMunicipality:
          type: object
          properties:
            code:
              type: string
            description:
              type: string
        relocators:
          type: array
          items:
            $ref: '#/components/schemas/Relocators'
    Partner:
      title: Partner
      x-stoplight:
        id: 47dyjopepond0
      type: object
      properties:
        bsn:
          type: string
        contactInformation:
          $ref: '#/components/schemas/ContactInformation'
        nameAfterCommitment:
          type: object
          properties:
            nameUseType:
              type: string
            title:
              type: string
            prefix:
              type: string
            lastname:
              type: string
    ContactInformation:
      title: ContactInformation
      x-stoplight:
        id: j1zkgz8stovvl
      type: object
      properties:
        email:
          type: string
        telephoneNumber:
          type: string
    Death:
      title: Death
      x-stoplight:
        id: 486cnp2x7lg1p
      type: object
      properties:
        dossier:
          $ref: '#/components/schemas/Dossier'
        declarant:
          $ref: '#/components/schemas/Declarant'
        deceased:
          type: object
          properties:
            bsn:
              type: string
              pattern: '^[0-9]*$'
            contactInformation:
              $ref: '#/components/schemas/ContactInformation'
            firstname:
              type: string
            prefix:
              type: string
            titlePredicate:
              type: string
            lastname:
              type: string
            birthdate:
              type: integer
            birthplace:
              type: string
            birthcountry:
              type: object
              properties:
                code:
                  type: string
                description:
                  type: string
        deathByNaturalCauses:
          type: boolean
        municipality:
          type: object
          properties:
            code:
              type: string
            description:
              type: string
        dateOfDeath:
          type: string
          format: date
        timeOfDeath:
          type: string
          description: '[0-9]{1,2}:[0-9]{2}'
          pattern: '[0-9]{1,2}:[0-9]{2}'
        funeralServices:
          type: object
          properties:
            serviceType:
              type: string
              enum:
                - BURIAL_CREMATION
                - DISSECTION
            date:
              type: string
              format: date
            time:
              type: string
              description: 'HH:mm'
            outsideBenelux:
              type: boolean
            causeOfDeathType:
              type: string
              enum:
                - NATURAL_CAUSES
                - NON_CONTAGIOUS_DISEASE
            countryOfDestination:
              type: object
              properties:
                code:
                  type: string
                description:
                  type: string
            placeOfDestination:
              type: string
            via:
              type: string
            transportation:
              type: string
        correspondence:
          type: object
          properties:
            communicationType:
              type: string
              enum:
                - EMAIL
                - POST
            organization:
              type: string
            departement:
              type: string
            name:
              type: string
            email:
              type: string
            telephoneNumber:
              type: string
            street:
              type: string
            houseNumber:
              type: integer
            houseNumberLetter:
              type: string
            houseNumberAddition:
              type: string
            postalCode:
              type: string
            residence:
              type: string
        extracts:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              description:
                type: string
              amount:
                type: integer
    Dossier:
      title: Dossier
      x-stoplight:
        id: sfx5fkesvalyq
      type: object
      properties:
        dossierId:
          type: string
        description:
          type: string
        referenceIds:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              description:
                type: string
        type:
          type: object
          properties:
            code:
              type: string
            description:
              type: string
        status:
          type: object
          properties:
            code:
              type: string
            description:
              type: string
            entryDateTime:
              type: string
              format: date-time
            endStatus:
              type: boolean
        startDate:
          type: string
          format: date
        entryDateTime:
          type: string
          format: date-time
    Declarant:
      title: Declarant
      x-stoplight:
        id: aa6gwd79ds0zw
      type: object
      properties:
        bsn:
          type: string
          maxLength: 9
          pattern: '^[0-9]*$'
        contactInformation:
          $ref: '#/components/schemas/ContactInformation'
    Birth:
      title: Birth
      x-stoplight:
        id: g8uhku7vbflmg
      type: object
      properties:
        dossier:
          $ref: '#/components/schemas/Dossier'
        qualificationForDeclaringType:
          type: string
          enum:
            - UNDERTAKER
            - FATHER
            - DUO_MOTHER
            - PRESENT_AT_BIRTH
            - BORN_IN_HOME
            - BORN_IN_INSTITUTION
            - MOTHER
            - MAYOR
            - KNOWLEDGE_CARRIER
        declarant:
          $ref: '#/components/schemas/Declarant'
        mother:
          type: object
          properties:
            bsn:
              type: string
              pattern: '^[0-9]*$'
            contactInformation:
              $ref: '#/components/schemas/ContactInformation'
        fatherDuoMother:
          type: object
          properties:
            bsn:
              type: string
              pattern: '^[0-9]*$'
            contactInformation:
              $ref: '#/components/schemas/ContactInformation'
        children:
          type: array
          items:
            type: object
            properties:
              firstname:
                type: string
              gender:
                type: string
                enum:
                  - MAN
                  - WOMAN
                  - UNKNOWN
              birthDateTime:
                type: string
                format: date-time
        nameSelection:
          type: object
          properties:
            lastname:
              type: string
            prefix:
              type: string
            titlePredicate:
              type: string
              enum:
                - B
                - BS
                - G
                - GI
                - H
                - HI
                - JH
                - JV
                - M
                - MI
                - P
                - PS
                - R
    NewAddress:
      title: NewAddress
      x-stoplight:
        id: peql1fbd51pmx
      type: object
      properties:
        street:
          type: string
        houseNumber:
          type: integer
        houseLetter:
          type: string
        houseNumberAddition:
          type: string
        postalCode:
          type: string
        residence:
          type: string
        municipality:
          type: object
          properties:
            code:
              type: string
            description:
              type: string
        addressFunction:
          type: string
          enum:
            - LIVING_ADDRESS
            - MAILING_ADDRESS
        numberOfResidents:
          type: integer
        destinationCurrentResidents:
          type: string
        liveIn:
          $ref: '#/components/schemas/liveIn'
        mainOccupant:
          type: object
          properties:
            bsn:
              type: string
            contactInformation:
              $ref: '#/components/schemas/ContactInformation'
    liveIn:
      title: liveIn
      x-stoplight:
        id: uwo793999peba
      type: object
      properties:
        liveInApplicable:
          type: boolean
        consent:
          type: string
          enum:
            - NOT_APPLICABLE
            - PENDING
            - APPROVED
            - DECLINED
        consenter:
          type: object
          properties:
            bsn:
              type: string
              pattern: '^[0-9]*$'
            contactInformation:
              $ref: '#/components/schemas/ContactInformation'
    Relocators:
      title: Relocators
      x-stoplight:
        id: 7pycr8953i0or
      type: object
      properties:
        bsn:
          type: string
        contactInformation:
          $ref: '#/components/schemas/ContactInformation'
        declarationType:
          type: string
          enum:
            - EX_OFFICIO
            - MINISTERIAL_DECISION
            - AUTHORITY_HOLDER
            - HEAD_OF_AN_INSTITUTION
            - REGISTERED
            - ADULT_CHILD_LIVING_WITH_PARENTS
            - ADULT_AUTHORIZED_REPRESENTATIVE
            - PARTNER
            - PARENT_LIVING_WITH_ADULT_CHILD
    Elementen:
      title: Elementen
      x-stoplight:
        id: u7gn05yf9munv
      type: object
      properties:
        bsn:
          type: string
        voorletters:
          type: string
        voorvoegsel:
          type: string
        achternaam:
          type: string
        geslacht:
          type: string
        straatnaam:
          type: string
        huisnummer:
          type: string
        postcode:
          type: string
        woonplaats:
          type: string
        telefoonnummer:
          type: string
        emailadres:
          type: string
        gemeentecode:
          type: string
        adresregel1:
          type: string
        adresregel2:
          type: string
        landcode:
          type: string
        datumVertrek:
          type: string
        straatnaam_nieuw:
          type: string
        huisnummer_nieuw:
          type: string
        huisletter_nieuw:
          type: string
        huisnummertoevoeging_nieuw:
          type: string
        woonplaats_nieuw:
          type: string
        postcode_nieuw:
          type: string
        verhuisdatum:
          type: string
        aantal_pers_nieuw_adres:
          type: string
        wijze_bewoning:
          type: string
        bsn_hoofdbewoner:
          type: string
        uittreksel:
          type: array
          items:
            $ref: '#/components/schemas/Uittreksel'
        bsn_geheimhouding:
          type: string
        code_geheimhouding:
          type: string
        meeverhuizende_gezinsleden:
          type: array
          items:
            $ref: '#/components/schemas/Meeverhuizers'
    Uittreksel:
      title: Uittreksel
      x-stoplight:
        id: rj5px9uptuxeq
      type: object
      properties:
        bsn:
          type: string
        code:
          type: string
        omschrijving:
          type: string
    Meeverhuizers:
      title: Meeverhuizers
      x-stoplight:
        id: uzke3kpeqtb87
      type: object
      properties:
        bsn:
          type: string
        rol:
          type: string
        voorletters:
          type: string
        voornaam:
          type: string
        achternaam:
          type: string
        geslachtsaanduiding:
          type: string
        geboortedatum:
          type: string
